"""GitHub issue creation via PyGithub.

Opens one issue per incident with Claude's full analysis as the body,
formatted as a Markdown runbook for on-call engineers.
"""

import logging
import os
from datetime import datetime, timezone

from github import Github, GithubException

logger = logging.getLogger(__name__)

_gh = Github(os.environ["GITHUB_TOKEN"])
_repo_name: str = os.environ["GITHUB_REPO"]  # owner/repo


def _build_issue_body(
    alert_name: str,
    severity: str,
    service: str,
    fired_at: datetime,
    root_cause: str,
    runbook: str,
    severity_assessment: str,
    logs_snapshot: str,
) -> str:
    fired_str = fired_at.strftime("%Y-%m-%d %H:%M:%S UTC")
    log_excerpt = "\n".join(logs_snapshot.splitlines()[:50])  # cap at 50 lines
    if len(logs_snapshot.splitlines()) > 50:
        log_excerpt += "\n… (truncated — see incident record for full log snapshot)"

    return f"""\
## Incident Summary

| Field | Value |
|---|---|
| **Alert** | `{alert_name}` |
| **Service** | `{service}` |
| **Severity** | {severity} |
| **Fired At** | {fired_str} |

---

## Root Cause

{root_cause}

---

## Severity Assessment

{severity_assessment}

---

{runbook}

---

## Log Snapshot (last 10 minutes)

<details>
<summary>Click to expand logs</summary>

```
{log_excerpt}
```

</details>

---

*This issue was auto-generated by [aiops-brain](https://github.com/{_repo_name}) \
using Claude AI analysis.*
"""


async def open_issue(
    alert_name: str,
    severity: str,
    service: str,
    fired_at: datetime,
    root_cause: str,
    runbook: str,
    severity_assessment: str,
    logs_snapshot: str,
) -> str | None:
    """Create a GitHub issue and return its HTML URL, or None on failure."""
    title = f"[{severity.upper()}] {alert_name} — {service}"
    body = _build_issue_body(
        alert_name=alert_name,
        severity=severity,
        service=service,
        fired_at=fired_at,
        root_cause=root_cause,
        runbook=runbook,
        severity_assessment=severity_assessment,
        logs_snapshot=logs_snapshot,
    )
    labels = ["incident", f"severity:{severity.lower()}"]

    try:
        repo = _gh.get_repo(_repo_name)
        issue = repo.create_issue(title=title, body=body, labels=labels)
        logger.info(
            "github_issue created url=%s alert=%s", issue.html_url, alert_name
        )
        return issue.html_url
    except GithubException as exc:
        logger.error(
            "github_issue failed alert=%s status=%s data=%s",
            alert_name,
            exc.status,
            exc.data,
        )
        return None
